// Writes *_v2.mjs copies of the opening's verifiers in which every single-precision sum,
// difference, quotient and square root goes through the exact routines of
// ../model/opening-lib.mjs (add, sub, quotient, root) instead of a double result cut to single.
// The double sum of two singles loses an addend more than 29 binary places smaller than the
// other, and a double quotient or root can round up onto a single; the EE's result is the exact
// one cut toward zero. Products need no change: the product of two singles is exact in double.
//
// node extract_opening_exact.mjs
import fs from 'node:fs';
import ts from 'file:///D:/CodingProjects/Watson/Server/node_modules/typescript/lib/typescript.js';

const NAMES = ['camera', 'camera_rom', 'cubes', 'fog', 'lights', 'towers', 'vu1'];
const here = new URL('.', import.meta.url);

function rewrite(source) {
  const file = ts.createSourceFile('x.mjs', source, ts.ScriptTarget.Latest, true, ts.ScriptKind.JS);
  const edits = [];
  const visit = (node) => {
    ts.forEachChild(node, visit);
    if (!ts.isCallExpression(node) || !ts.isIdentifier(node.expression) || node.expression.text !== 'f' || node.arguments.length !== 1) return;
    let inner = node.arguments[0];
    while (ts.isParenthesizedExpression(inner)) inner = inner.expression;
    const text = (n) => source.slice(n.getStart(file), n.end);
    if (ts.isBinaryExpression(inner)) {
      const op = inner.operatorToken.kind;
      const name = op === ts.SyntaxKind.PlusToken ? 'add' : op === ts.SyntaxKind.MinusToken ? 'sub' : op === ts.SyntaxKind.SlashToken ? 'quotient' : null;
      if (name) edits.push({ start: node.getStart(file), end: node.end, left: inner.left, right: inner.right, name });
    } else if (ts.isCallExpression(inner) && text(inner.expression) === 'Math.sqrt' && inner.arguments.length === 1) {
      edits.push({ start: node.getStart(file), end: node.end, left: inner.arguments[0], name: 'root' });
    }
  };
  visit(file);
  // Apply innermost first by rebuilding each edited call from its (already edited) operands.
  const render = (start, end) => {
    let out = '', at = start;
    const inside = edits.filter((x) => x.start >= start && x.end <= end).sort((a, b) => a.start - b.start);
    for (const e of inside.filter((x) => !inside.some((y) => y !== x && y.start <= x.start && y.end >= x.end))) {
      out += source.slice(at, e.start) + one(e);
      at = e.end;
    }
    return out + source.slice(at, end);
  };
  const one = (e) => e.name === 'root' ? `exactRoot(${render(e.left.getStart(file), e.left.end)})` : `exact${e.name[0].toUpperCase() + e.name.slice(1)}(${render(e.left.getStart(file), e.left.end)}, ${render(e.right.getStart(file), e.right.end)})`;
  return { text: render(0, source.length), count: edits.length };
}

for (const name of NAMES) {
  const from = `verify_opening_${name}.mjs`, to = `verify_opening_${name}_v2.mjs`;
  let source = fs.readFileSync(new URL(from, here), 'utf8');
  const { text, count } = rewrite(source);
  let out = text
    .replace(/import \{ f \} from '\.\.\/model\/clock_frame\.mjs';/, "import { f, add as exactAdd, sub as exactSub, quotient as exactQuotient, root as exactRoot } from '../model/opening-lib.mjs';")
    .replace(/endsWith\('verify_opening_([a-z_0-9]+)\.mjs'\)/g, "endsWith('verify_opening_$1_v2.mjs')");
  for (const other of NAMES) out = out.replaceAll(`'./verify_opening_${other}.mjs'`, `'./verify_opening_${other}_v2.mjs'`);
  out = `// Generated by extract_opening_exact.mjs from ${from}: exact single-precision add, sub, quotient, root.\n` + out;
  fs.writeFileSync(new URL(to, here), out);
  console.log(`${to}: ${count} operations made exact`);
}
