// Generated by extract_opening_exact.mjs from verify_opening_fog.mjs: exact single-precision add, sub, quotient, root.
// The fog of the opening intro (HDD OSD 1.10U, OpeningDrawFog 0x0021E168): six layers of a
// 16 x 16 quad mesh, each with its own scrolling texture, recomputed from the state at the
// function's entry and compared with the packets it sent, write by write.
//
//   0x0021E168  entry: the scroll offsets, the mesh and its colours, the textures' table, the
//               clip box, the world-to-screen matrix, the blend modes' table (A, B, C, D per mode)
//
// node verify_opening_fog.mjs <trace.jsonl>
import { readTraceFor } from '../lib/trace.mjs';
// On a capture shared with other verifiers, only this verifier's probe records.
const readTrace = (file) => readTraceFor(file, PROBES);
import { GifPath } from 'file:///D:/CodingProjects/Watson/Server/dist/gs/gif.js';
import { f, add as exactAdd, sub as exactSub, quotient as exactQuotient, root as exactRoot } from '../model/opening-lib.mjs';
import { transformVertex, clipAll, vector, matrix, floatBits, toInt, pack } from './verify_opening_lights_v2.mjs';

// 0x003D80A0: six scroll offsets; 0x003D80C0: 17 x 17 positions; 0x003D92D0: 17 x 17 colours.
export const PROBES = [
  { pc: '0x0021e168', ranges: ['0x003d80a0:0x2440', '0x0036f990:0x4', '0x003653e8:0x18', '0x002af870:0x5a0', '0x002b0c20:0x20', '0x70000120:0x40', '0x002b0cc0:0xb0'] },
];
const ENTRY = parseInt(PROBES[0].pc, 16);
const REG = { PRIM: 0, RGBAQ: 1, ST: 2, XYZF2: 4, TEX0: 6, ALPHA: 0x42, PABE: 0x49 };

export function expected(input) {
  const { mesh, step, order, textures, clip, toScreen, modes } = input;
  // pktSetAlphaBlend (0x0021B9C8): the mode's four selectors and the fixed value.
  const blend = (mode, fix) => BigInt(modes.readInt32LE(mode * 16) | (modes.readInt32LE(mode * 16 + 4) << 2) | (modes.readInt32LE(mode * 16 + 8) << 4) | (modes.readInt32LE(mode * 16 + 12) << 6)) | (BigInt(fix) << 32n);
  const [min, max] = [vector(clip, 0), vector(clip, 0x10)];
  const m = matrix(toScreen, 0);
  const packets = [];
  const scrolls = [];
  let drawn = 0, clipped = 0;
  for (let layer = 0; layer < 6; layer++) {
    // The layer's texture moves by (14 - layer) x step x (layer + 1) / 2 a frame, wrapping at 1.
    let scroll = exactAdd(mesh.readFloatLE(layer * 4), f(f(f(exactSub(14, layer) * step) * exactAdd(layer, 1)) * 0.5));
    if (1 < scroll) scroll = exactSub(scroll, 1);
    scrolls.push(scroll);
    const fix = toInt(f(f(128 * 20) * 0.0078125));
    const texture = textures.readUInt32LE(order.readInt32LE((layer % 6) * 4) * 0xf0 + 0x60);
    packets.push({ label: 'state', writes: [[REG.TEX0, BigInt((texture | 0x18204000) >>> 0) | (0xb000n << 19n)], [REG.PABE, 0n], [REG.ALPHA, blend(0, fix)]] });
    const drop = f(f(layer) * 5);
    for (let row = 0; row < 16; row++) {
      const writes = [];
      for (let column = 0; column < 16; column++) {
        const at = (k) => (row + (k >> 1)) * 16 + (column + (k & 1)) * 0x110;
        const corners = [0, 1, 2, 3].map((k) => { const v = vector(mesh, 0x20 + at(k)); return [v[0], v[1], exactSub(v[2], drop), v[3]]; });
        if (clipAll(min, max, m, corners) !== 0) { clipped += 1; continue; }
        drawn += 1;
        writes.push([REG.PRIM, 0x5cn]);
        corners.forEach((corner, k) => {
          const { ints, q } = transformVertex(m, corner);
          const across = f(exactAdd(f(f(k >> 1) * 0.5), f(f(row & 1) * 0.5)) * q);
          const along = f(exactSub(exactAdd(f(f(k & 1) * 0.5), f(f(column & 1) * 0.5)), scroll) * q);
          const level = mesh.readInt32LE(0x1230 + at(k) + 8);
          const colour = BigInt.asUintN(64, BigInt(level < 0 ? (level + 3) >> 2 : level >> 2) | (BigInt(Math.trunc((level * 2) / 5)) << 8n) | (BigInt(level) << 16n) | 0x80000000n | (BigInt(floatBits(q)) << 32n));
          writes.push([REG.ST, BigInt(floatBits(along)) | (BigInt(floatBits(across)) << 32n)], [REG.RGBAQ, colour], [REG.XYZF2, pack(ints[0], ints[1], ints[2])]);
        });
      }
      packets.push({ label: `layer ${layer} row ${row}`, writes });
    }
  }
  return { packets, scrolls, drawn, clipped };
}

export function verify(traceFile) {
  const trace = readTrace(traceFile);
  if (!trace.complete) throw new Error(`${traceFile}: ${trace.reason}`);
  const result = { frames: 0, packets: [0, 0], writes: [0, 0], drawn: 0, clipped: 0, scrolls: [0, 0], problems: [] };
  const problem = (text) => { if (result.problems.length < 12) result.problems.push(text); };
  const writesOf = (packet) => [...new GifPath().feed(packet.bytes)].filter((event) => event.kind === 'write');

  const entries = trace.probes.filter((probe) => probe.pc === ENTRY && !probe.preroll);
  let previous = null;
  entries.forEach((entry, n) => {
    const next = entries[n + 1];
    if (entry.mem.some((range) => !range.bytes)) { problem(`frame ${entry.frame}: a probed range was not readable`); return; }
    const [mesh, step, order, textures, clip, toScreen, modes] = entry.mem.map((range) => range.bytes);
    const model = expected({ mesh, step: step.readFloatLE(0), order, textures, clip, toScreen, modes });
    // The offsets the next call finds are the ones this call left.
    if (previous) previous.forEach((scroll, layer) => { result.scrolls[1] += 1; if (floatBits(scroll) === floatBits(mesh.readFloatLE(layer * 4))) result.scrolls[0] += 1; else problem(`frame ${entry.frame}: layer ${layer} offset ${mesh.readFloatLE(layer * 4)}, computed ${scroll}`); });
    previous = model.scrolls;
    // The call sends: depth write off, CLAMP, TEX1, then per layer one state packet and sixteen rows.
    const first = entry.at + 3;
    if (first + model.packets.length > (next ? next.at : trace.packets.length)) return;
    result.frames += 1;
    result.drawn += model.drawn; result.clipped += model.clipped;
    model.packets.forEach((packet, k) => {
      const sent = writesOf(trace.packets[first + k]);
      result.packets[1] += 1;
      result.writes[1] += packet.writes.length;
      let equal = sent.length === packet.writes.length, bad = null;
      packet.writes.forEach(([reg, value], w) => { if (sent[w] && sent[w].reg === reg && sent[w].value === value) result.writes[0] += 1; else { equal = false; bad ??= w; } });
      if (equal) result.packets[0] += 1;
      else problem(`frame ${entry.frame} ${packet.label}: ${sent.length} writes sent, ${packet.writes.length} computed${bad === null ? '' : `; write ${bad}: sent ${sent[bad] ? `reg 0x${sent[bad].reg.toString(16)} = 0x${sent[bad].value.toString(16)}` : 'nothing'}, computed reg 0x${packet.writes[bad][0].toString(16)} = 0x${packet.writes[bad][1].toString(16)}`}`);
    });
  });
  return result;
}

if (process.argv[1] && process.argv[1].endsWith('verify_opening_fog_v2.mjs')) {
  const result = verify(process.argv[2]);
  console.log(`frames compared: ${result.frames}`);
  console.log(`  packets equal: ${result.packets[0]} of ${result.packets[1]} (writes ${result.writes[0]} of ${result.writes[1]}); quads drawn ${result.drawn}, left out by the clip test ${result.clipped}`);
  console.log(`  scroll offsets carried to the next frame: ${result.scrolls[0]} of ${result.scrolls[1]}`);
  for (const text of result.problems) console.log(`  ! ${text}`);
  const whole = result.frames > 0 && result.problems.length === 0;
  console.log(`verdict: ${whole ? `FOUND ${result.frames} frames of the opening's fog, every write equal` : 'PARTIAL see the lines marked !'}`);
  process.exit(whole ? 0 : 3);
}
