if(NOT EXISTS ${EXE})
    message(STATUS "${EXE} is not built: skipped")
    cmake_language(EXIT 77)
endif()
file(REMOVE_RECURSE ${SCRATCH})
file(MAKE_DIRECTORY ${SCRATCH}/resources)
execute_process(COMMAND ${EXE} --resources ${SCRATCH}/resources --assets ${SCRATCH}/assets.bin
    RESULT_VARIABLE CODE OUTPUT_VARIABLE OUT ERROR_VARIABLE ERR TIMEOUT 60)
if(NOT CODE EQUAL 1)
    message(FATAL_ERROR "expected exit code 1, got ${CODE}\n${OUT}\n${ERR}")
endif()
foreach(NEEDLE "missing:" "--bios rom.bin" "--resources dir")
    string(FIND "${ERR}" "${NEEDLE}" AT)
    if(AT LESS 0)
        message(FATAL_ERROR "stderr lacks '${NEEDLE}':\n${ERR}")
    endif()
endforeach()
